site_name: pysimdeum
nav:
  - Home: index.md
  - Installation: installation.md
  - quick_start.md
  - pysimdeum_run.md
  - Examples:
      - Overview: !include examples/1_intro_to_pysimdeum.ipynb
      - Consumption object: !include examples/2_consumption_object.ipynb
      - Discharge object: !include examples/3_discharge_object.ipynb
      - Multiday simulations and spillover: !include examples/4_multiday_sims_and_spillover.ipynb
      - Wastewater quality: !include examples/5_wastewater_quality.ipynb
      - Writing data: !include examples/6_writing_data.ipynb
  - Consumption:
    - Overview: consumption/overview.md
    - Common methods: consumption/common_methods.md
    - Enduse specifics: consumption/enduse_specifics.md
  - Discharge:
    - Overview: discharge/overview.md
    - Common methods: discharge/common_methods.md
    - Enduse specifics: discharge/enduse_specifics.md
    - Water quality: discharge/water_quality.md
  - config.md
  - Config Schema: schema.md
  - Changelog: CHANGELOG.md
theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.indexes
    - navigation.top
    - content.code.copy
    - content.code.annotate
repo_url: https://github.com/KWR-Water/pysimdeum
site_dir: .docs
markdown_extensions:
  - admonition
  - attr_list
  - mkdocs-click
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      clickable_checkbox: true
  - toc:
      permalink: "#"
      toc_depth: 3
plugins:
  - search
  - autorefs
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_section_style: spacy
            show_bases: true
            filters:
              - "!^_"
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
            show_root_toc_entry: false
            show_signature_annotations: false
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://shapely.readthedocs.io/en/stable/objects.inv
            - https://geopandas.org/en/stable/objects.inv
watch:
  - pysimdeum/core
extra_css:
  - static/extras.css
extra:
  version:
    provider: mike